# fly.toml app configuration file generated for go-monitoring on 2025-03-20T15:03:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-monitoring'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.20'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
